# Generated by Django 4.1.5 on 2023-01-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'статистика за день',
                'verbose_name_plural': 'статистика за день',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('emotion', models.CharField(choices=[('happy', 'Счастье'), ('sad', 'Грусть'), ('scared', 'Страх'), ('disappointed', 'Разочарование'), ('angry', 'Злость')], max_length=20, verbose_name='эмоция')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.daystats', verbose_name='день')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
