# Generated by Django 4.1.5 on 2023-01-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.daystats', verbose_name='статистика за день'),
        ),
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='время'),
        ),
    ]
